### ISSUE TITLE
I encounter a problem with Offdroid.

### ISSUE THREAD

**Issue by leonleeann** [icefapper/offdroid#1]
When I issue the command "offdroid list-packages", I received some error message as follow.
# offdroid list-packages

<ARGUMENTS>
<.offdroid-xml/.offdroid-urlmap>: <.offdroid-xml/.offdroid-filemap>

</ARGUMENTS>

<ARGUMENTS>
<.offdroid-xml/.offdroid-urlmap>: <.offdroid-xml/.offdroid-filemap>

</ARGUMENTS>

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '.sources'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at repo (/android/offdroid/get-addons.js:37:8)
    at extract (/android/offdroid/get-addons.js:24:5)
    at Object.<anonymous> (/android/offdroid/get-addons.js:209:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
LISTING FINISHED

What should I do, Thank you very much.
BTW, this project is a great great project to us Chinese, because of the GFW of China gov.

**Comment by leonleeann** [comment]
My solution is that I create ".sources" by myself,  it looks like work well as so far.

**Comment by icefapper** [comment]
Wow @leonleeann!
It is indeed a pleasure to hear offdroid has been of actual use to someone.
I just got the issue fixed (silly me.) I hope it now works as it should.

Also, thanks for your feedback -- that is just what I need!
